# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  # Enable version updates for npm

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/compose/minio-init"
    # Check for updates once a week
    schedule:
      interval: "weekly"
