---
version: '3.8'


services:
  mongodb:
    image: mongo:latest

  postgres:
    image: postgres:latest

  dserver:
    image: jotelha/dserver:latest

  token_generator_ldap:
    image: jotelha/dtool-token-generator-ldap:0.2.2
