version: '3.8'

services:
  mongodb:
    expose:
      - 21017

  postgres:
    expose:
      - 5433

  dtool_lookup_server:
    expose:
      - 5000

  dtool_lookup_webapp:
    expose:
      - 443

  token_generator_ldap:
    expose:
      - 5001

  web:
    ports:
     - "80:80"
     - "443:443"
    environment:
     - NGINX_HOST=livmats-data.vm.uni-freiburg.de
     - NGINX_PORT=80
     - NGINX_SSL_PORT=443
