version: '2'

services:
  mongodb:
    expose:
      - 21017

  postgres:
    expose:
      - 5433

  dtool_lookup_server:
    ports:
      - "5100:5000"

  token_generator_ldap:
    ports:
      - "5101:5001"
