---
version: '3.8'

services:

  dtool_lookup_server:
    depends_on:
      omgwtfssl-dtool-lookup-server:
        condition: service_started

  omgwtfssl-dtool-lookup-server:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    depends_on:
      volume_init:
        condition: service_completed_successfully
    environment:
      - CA_SUBJECT=${ADMINMAIL:-admin@dtool-lookup-server.provider}
      - CA_KEY=ca-key.pem
      - CA_CERT=CAs/ca.pem
      - SSL_SUBJECT=dtool-lookup-server
      - SSL_DNS=${HOSTNAME:-localhost},dtool-lookup-server
      - SSL_KEY=dtool-lookup-server.key
      - SSL_CSR=dtool-lookup-server.csr
      - SSL_CERT=dtool-lookup-server.crt
    volumes:
      - cert_data:/certs

  omgwtfssl-token-generator-ldap:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    depends_on:
      omgwtfssl-dtool-lookup-server:
        condition: service_completed_successfully
    environment:
      - CA_SUBJECT=${ADMINMAIL:-admin@dtool-lookup-server.provider}
      - CA_KEY=ca-key.pem
      - CA_CERT=CAs/ca.pem
      - SSL_SUBJECT=token-generator-ldap
      - SSL_DNS=${HOSTNAME:-localhost},token-generator-ldap
      - SSL_KEY=token-generator-ldap.key
      - SSL_CSR=token-generator-ldap.csr
      - SSL_CERT=token-generator-ldap.crt
    volumes:
      - cert_data:/certs

  omgwtfssl-dtool-lookup-webapp:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    depends_on:
      omgwtfssl-dtool-lookup-server:
        condition: service_completed_successfully
    environment:
      - CA_SUBJECT=${ADMINMAIL:-admin@dtool-lookup-server.provider}
      - CA_KEY=ca-key.pem
      - CA_CERT=CAs/ca.pem
      - SSL_SUBJECT=dtool-lookup-webapp
      - SSL_DNS=${HOSTNAME:-localhost},dtool-lookup-webapp
      - SSL_KEY=dtool-lookup-webapp.key
      - SSL_CSR=dtool-lookup-webapp.csr
      - SSL_CERT=dtool-lookup-webapp.crt
    volumes:
      - cert_data:/certs

  web:
    environment:
      - NGINX_SSL_CERT=/certs/dtool-lookup-server.crt
      - NGINX_SSL_KEY=/certs/dtool-lookup-server.key
