version: '3.8'

services:

  dtool_lookup_server:
    depends_on:
      omgwtfssl-dtool-lookup-server:
        condition: service_started

  omgwtfssl-dtool-lookup-server:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    volumes:
      - cert_data:/certs

  omgwtfssl-token-generator-ldap:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    depends_on:
      omgwtfssl-dtool-lookup-server:
        condition: service_completed_successfully
    volumes:
      - cert_data:/certs

  omgwtfssl-dtool-lookup-webapp:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    depends_on:
      omgwtfssl-dtool-lookup-server:
        condition: service_completed_successfully
    volumes:
      - cert_data:/certs

