---
version: '3.8'

services:

  s3server:
    depends_on:
      omgwtfssl-s3server:
        condition: service_completed_successfully

  omgwtfssl-s3server:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    environment:
      - CA_SUBJECT=${ADMINMAIL:-admin@dserver.provider}
      - CA_KEY=ca-key.pem
      - CA_CERT=CAs/ca.pem
      - SSL_SUBJECT=s3server
      - SSL_DNS=${HOSTNAME:-localhost},s3server
      - SSL_KEY=s3server.key
      - SSL_CSR=s3server.csr
      - SSL_CERT=s3server.crt
    depends_on:
      omgwtfssl-dserver:
        condition: service_completed_successfully
    volumes:
      - cert_data:/certs
