---
version: '3.8'

services:
  mongodb:
    expose:
      - 21017

  postgres:
    expose:
      - 5433

  dtool_lookup_server:
    expose:
      - 5000

  dtool_lookup_webapp:
    expose:
      - 80
      - 443
    environment:
      - NGINX_HOST=dtool-lookup-webapp
      - NGINX_PORT=80
      - NGINX_SSL_PORT=443
      - VUE_APP_DTOOL_LOOKUP_SERVER_URL="https://$HOSTNAME:4443/lookup"
      - VUE_APP_DTOOL_LOOKUP_SERVER_TOKEN_GENERATOR_URL="https://$HOSTNAME:4443/token"

  token_generator_ldap:
    expose:
      - 5001

  web:
    ports:
      - "8080:8080"
      - "4443:4443"
    environment:
      - NGINX_HOST=$HOSTNAME
      - NGINX_PORT=8080
      - NGINX_SSL_PORT=4443
