---
services:

  dserver:
    depends_on:
      omgwtfssl-dserver:
        condition: service_started

  omgwtfssl-dserver:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    depends_on:
      volume_init:
        condition: service_completed_successfully
    environment:
      - CA_SUBJECT=${ADMINMAIL:-admin@dserver.provider}
      - CA_KEY=ca-key.pem
      - CA_CERT=CAs/ca.pem
      - SSL_SUBJECT=dserver
      - SSL_DNS=${HOSTNAME:-localhost},dserver,web
      - SSL_KEY=dserver.key
      - SSL_CSR=dserver.csr
      - SSL_CERT=dserver.crt
    volumes:
      - cert_data:/certs

  omgwtfssl-token-generator-ldap:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    depends_on:
      omgwtfssl-dserver:
        condition: service_completed_successfully
    environment:
      - CA_SUBJECT=${ADMINMAIL:-admin@dserver.provider}
      - CA_KEY=ca-key.pem
      - CA_CERT=CAs/ca.pem
      - SSL_SUBJECT=token-generator-ldap
      - SSL_DNS=${HOSTNAME:-localhost},token-generator-ldap,web
      - SSL_KEY=token-generator-ldap.key
      - SSL_CSR=token-generator-ldap.csr
      - SSL_CERT=token-generator-ldap.crt
    volumes:
      - cert_data:/certs

  omgwtfssl-dtool-lookup-webapp:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    depends_on:
      omgwtfssl-dserver:
        condition: service_completed_successfully
    environment:
      - CA_SUBJECT=${ADMINMAIL:-admin@dserver.provider}
      - CA_KEY=ca-key.pem
      - CA_CERT=CAs/ca.pem
      - SSL_SUBJECT=dtool-lookup-webapp
      - SSL_DNS=${HOSTNAME:-localhost},dtool-lookup-webapp,web
      - SSL_KEY=dtool-lookup-webapp.key
      - SSL_CSR=dtool-lookup-webapp.csr
      - SSL_CERT=dtool-lookup-webapp.crt
    volumes:
      - cert_data:/certs

  web:
    environment:
      - NGINX_SSL_CERT=/certs/dserver.crt
      - NGINX_SSL_KEY=/certs/dserver.key
