version: '3.8'

volumes:
  cert_data_mailu: {}

services:
  acme-mailu:
    image: neilpang/acme.sh:latest
    restart: "no"
    command: >-
      acme.sh --install-cert -d ${DOMAIN}
              --cert-file      /certs/cert.pem
              --key-file       /certs/key.pem
              --ca-file        /certs/ca.pem
              --fullchain-file /certs/full-chain.pem
    volumes:
      - type: volume
        source: cert_data_mailu
        target: /certs
      - type: bind
        source: $HOME/acme.sh
        target: /acme.sh
        read_only: true

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "./mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: ./envs/production/mailu
    logging:
      driver: json-file
    expose:
      - "80"
      - "443"
    ports:
      # - "${BIND}:8080:80"
      # - "${BIND}:8443:443"
      - "${BIND}:25:25"
      - "${BIND}:465:465"
      - "${BIND}:587:587"
      - "${BIND}:110:110"
      - "${BIND}:995:995"
      - "${BIND}:143:143"
      - "${BIND}:993:993"
    volumes:
      - type: volume
        source: cert_data_mailu
        target: /certs
      - "./mailu/overrides/nginx:/overrides:ro"
    depends_on:
      resolver:
        condition: service_started
      acme:
        condition: service_completed_successfully
    dns:
      - 192.168.203.254
    networks:
      default:
        ipv4_address: 192.168.203.111

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: ./envs/production/mailu
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    restart: always
    env_file: ./envs/production/mailu
    volumes:
      - "./mailu/data:/data"
      - "./mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: always
    env_file: ./envs/production/mailu
    volumes:
      - "./mailu/mail:/mail"
      - "./mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
    restart: always
    env_file: ./envs/production/mailu
    volumes:
      - "./mailu/mailqueue:/queue"
      - "./mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
    hostname: antispam
    restart: always
    env_file: ./envs/production/mailu
    volumes:
      - "./mailu/filter:/var/lib/rspamd"
      - "./mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  # Optional services



  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.9}
    restart: always
    env_file: ./envs/production/mailu
    volumes:
      - "./mailu/webmail:/data"
      - "./mailu/overrides/roundcube:/overrides:ro"
    depends_on:
      - imap
      - resolver
    dns:
      - 192.168.203.254

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24

