version: '3.8'

services:
  mongodb:
    expose:
      - 21017

  postgres:
    expose:
      - 5433

  dtool_lookup_server:
    ports:
      - "5100:5000"

  dtool_lookup_webapp:
    ports:
      - "8080:80"
      - "4443:443"

  token_generator_ldap:
    ports:
      - "5101:5001"
