version: '3.8'

services:

  dtool_lookup_server:
    depends_on:
      omgwtfssl-dtool-lookup-server:
        condition: service_started

  omgwtfssl-dtool-lookup-server:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    env_file:
      - ./envs/production/omgwtfssl_dtool_lookup_server
    volumes:
      - cert_data:/certs

  omgwtfssl-token-generator-ldap:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    depends_on:
      omgwtfssl-dtool-lookup-server:
        condition: service_completed_successfully
    env_file:
      - ./envs/production/omgwtfssl_token_generator_ldap
    volumes:
      - cert_data:/certs

  omgwtfssl-dtool-lookup-webapp:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    depends_on:
      omgwtfssl-dtool-lookup-server:
        condition: service_completed_successfully
    env_file:
      - ./envs/production/omgwtfssl_dtool_lookup_webapp
    volumes:
      - cert_data:/certs
