---
version: '3.8'

services:

  dtool_lookup_server:
    depends_on:
      acme:
        condition: service_completed_successfully

  token_generator_ldap:
    depends_on:
      acme:
        condition: service_completed_successfully

  front:
    depends_on:
      acme-mailu:
        condition: service_completed_successfully

  acme:
    image: neilpang/acme.sh:latest
    restart: "no"
    command: >-
      acme.sh --install-cert -d ${HOSTNAME:-localhost}
              --cert-file      /certs/acme.crt
              --key-file       /certs/acme.key
              --ca-file        /certs/CAs/acme-ca.pem
              --fullchain-file /certs/CAs/acme-full-chain.pem
    depends_on:
      volume_init:
        condition: service_completed_successfully
    volumes:
      - type: volume
        source: cert_data
        target: /certs
      - type: bind
        source: $HOME/acme.sh
        target: /acme.sh
        read_only: true

  # failed to modify the default storage location of certs  in mailu, hence just use another volume with different structure her
  acme-mailu:
    image: neilpang/acme.sh:latest
    restart: "no"
    command: >-
      acme.sh --install-cert -d ${DOMAIN}
              --cert-file      /certs/cert.pem
              --key-file       /certs/key.pem
              --ca-file        /certs/ca.pem
              --fullchain-file /certs/full-chain.pem
    volumes:
      - type: volume
        source: cert_data_mailu
        target: /certs
      - type: bind
        source: $HOME/acme.sh
        target: /acme.sh
        read_only: true

  web:
    environment:
      - NGINX_SSL_CERT=/certs/acme.crt
      - NGINX_SSL_KEY=/certs/acme.key
