---
version: '3.8'

services:
  mongodb:
    expose:
      - 21017

  postgres:
    expose:
      - 5432

  dtool_lookup_server:
    expose:
      - 5000

  dtool_lookup_webapp:
    expose:
      - 80
      - 443
    environment:
      - NGINX_HOST=dtool-lookup-webapp
      - NGINX_PORT=80
      - NGINX_SSL_PORT=443
      - VUE_APP_DTOOL_LOOKUP_SERVER_URL=https://${HOSTNAME:-localhost}:${EXTERNAL_HTTPS_PORT:-443}/lookup
      - VUE_APP_DTOOL_LOOKUP_SERVER_TOKEN_GENERATOR_URL=https://${HOSTNAME:-localhost}:${EXTERNAL_HTTPS_PORT:-443}/token

  token_generator_ldap:
    expose:
      - 5001

  web:
    ports:
      - "${EXTERNAL_HTTP_PORT:-80}:${EXTERNAL_HTTP_PORT:-80}"
      - "${EXTERNAL_HTTPS_PORT:-443}:${EXTERNAL_HTTPS_PORT:-443}"
    environment:
      - NGINX_HOST=${HOSTNAME:-localhost}
      - NGINX_PORT=${EXTERNAL_HTTP_PORT:-80}
      - NGINX_SSL_PORT=${EXTERNAL_HTTPS_PORT:-443}
