version: '3.8'

services:
  s3server:
    depends_on:
      omgwtfssl-s3server:
        condition: service_completed_successfully

  omgwtfssl-dtool-lookup-server:
    depends_on:
      volume_init:
        condition: service_completed_successfully

  omgwtfssl-s3server:
    image: paulczar/omgwtfssl:latest
    restart: "no"
    env_file:
      - ./envs/production/omgwtfssl_s3server
    depends_on:
      omgwtfssl-dtool-lookup-server:
        condition: service_completed_successfully
    volumes:
      - cert_data:/certs
