#!/bin/bash -x
set -euxo pipefail

exec > /var/log/refresh_index.log
exec 2>&1

. /refresh_index.envs
export $(cut -d' ' -f3 /refresh_index.envs | cut -d= -f1)

printenv

flask base_uri list

# Build the index of the data on the URI
flask base_uri index smb://test-share
