name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    uses: livMatS/dtool-framework-workflows/.github/workflows/dserver-container-composition-test.yml@main
