name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    uses: jotelha/dtool-framework-workflows/.github/workflows/dtool-lookup-server-container-composition-test.yml@master
